---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# invitroTKdata

<!-- badges: start -->
<!-- badges: end -->

## Welcome to the GitHub repository for the invitroTKdata package

The `invitroTKdata` R package contains a collection of datasets collection of datasets containing a variety of in vitro toxicokinetic measurements including -- but not limited to -- chemical fraction unbound in the presence of plasma (f~up~), intrinsic hepatic clearance (Cl~int~), and membrane permeability for oral absorption (Caco2). The datasets provided by the package were processed and analyzed with the companion `invitroTKstats` package

If you are interested in contributing or want to report a bug, please submit a issue or start a discussion.

### Installation

* Installing the current version of the package from GitHub, run the following command:

``` r
devtools::install_github("<TBD>")
```

* Installing a local clone of the GitHub repo:

  1. Go to the GitHub repo for [`invitroTKdata`]("TBD")
  2. Choose the "Code" button and copy the repo URL.
  3. In your local command line terminal, navigate to the directory location you wish to store your local copy of the repo.
  4. In your terminal type `git clone <TBD>`.
  5. After cloning completes then open an R session.
  6. In the R console use the follwing commands:
  
```r
devtools::install_local(
  "<file_path_to_invitroTKstats_repo>/invitroTKdata"
)
```

* Installation may also be done via the RStudio provided 'Install Packages' menu under the 'Tools' tab.

### Loading the Package

To load the `invitroTKdata` data R package into your local R session via the R console:

```r
library(invitroTKdata)
```

Check the package version installed and in use:

```r
packageVersion(invitroTKdata)
```

## Contributors

* Sarah E. Davidson-Fritz (Conceptualization & Lead Package Developer)
* John Wambaugh (Conceptualization, Data Processing, & Subject Matter Expert)
* Lindsay Knupp (Software Development)
* Barbara A. Wetmore (Raw Data Generation & Subject Matter Expert)
* Anna Kreutz (Raw Data Generation)
* Marci Smeltz (Raw Data Generation)
* David Crizer (Raw Data Generation)

## Disclaimer

The United States Environmental Protection Agency (EPA) GitHub project code is provided on an "as is" basis and the user assumes responsibility for its use. EPA has relinquished control of the information and no longer has responsibility to protect the integrity, confidentiality, or availability of the information. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by EPA. The EPA seal and logo shall not be used in any manner to imply endorsement of any commercial product or activity by EPA or the United States Government.
